game:
  debug: True # Makes jobs complete instantly
  server:
    port: 6060
  general:
    resources:
      - gold
      - wood
      - stone
    storage: # Free storage
      gold: 1000
      wood: 1000
    start: # Starting resources
      gold: 1000
      units:
        -
          type: peasant
          level: 1
        -
          type: peasant
          level: 1
  building:
    palace:
      name: Palace
      levels:
        -
          cost:
            gold: 100
            wood: 100
            stone: 0
            time: 30
          requirements: {}
        -
          cost:
            gold: 500
            wood: 500
            stone: 100
            time: 120
          requirements: {}
    barracks:
      name: Barracks
      levels:
        -
          cost:
            gold: 50
            wood: 200
            time: 300
          requirements: {}
    goldmine:
      name: Gold Mine
      production: gold
      levels:
        -
          rate: 1 # Resources / second
          cost:
            gold: 20
            wood: 100
            time: 10
          requirements: {}
    vault:
      name: vault
      storage: gold
      levels:
        -
          capacity: 1000
          cost:
            wood: 10
            time: 10
          requirements: {}
    library:
      name: Library
      levels:
        -
          cost:
            gold: 1000
            wood: 1000
            time: 7200
          requirements: {}
        -
          cost:
            gold: 10000
            wood: 1000
            stone: 1000
            time: 43200 # 12 * 3600
          requirements: {}
  unit:
    peasant:
      name: Peasant
      levels:
        -
          hp: 1
          damage: 1
          range: 1
          speed: 1
          cost:
            gold: 100
            time: 1
          requirements: {}
    footman:
      name: Footman
      levels:
        -
          hp: 10
          damage: 3
          range: 1
          speed: 2
          cost:
            gold: 10
            time: 10
          requirements:
            buildings:
              barracks: 1
    archer:
      name: Archer
      levels:
        -
          hp: 6
          damage: 2
          range: 5
          speed: 3
          cost:
            gold: 5
            wood: 5
            time: 10
          requirements:
            buildings:
              barracks: 1
  missions:
    -
      name: Got wood?
      type: gather
      cost:
        time: 5
      units:
        peasant: 3
      rewards:
        resources:
          wood: 200
      requirements: {}
